# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-19 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('payment', 'payment'), ('update', 'budget update')], default='payment', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('time_in', models.TimeField(verbose_name='Time In')),
                ('time_out', models.TimeField(verbose_name='Time Out')),
                ('paid', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('usertype', models.CharField(choices=[('R', 'RA'), ('S', 'Secretary'), ('A', 'Admin')], default='R', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='records',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.User'),
        ),
        migrations.AddField(
            model_name='payments',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.Records'),
        ),
    ]
