# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-19 05:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payments',
            new_name='Payment',
        ),
        migrations.RenameModel(
            old_name='Records',
            new_name='Record',
        ),
    ]
