# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-19 05:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_auto_20180619_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='usertype',
            new_name='user_type',
        ),
    ]
