# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-22 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='time_out',
            field=models.TimeField(blank=True, null=True, verbose_name='Time Out'),
        ),
    ]
