# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-26 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_auto_20180622_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rate_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
