# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-27 05:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0003_customuser_rate_per_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='username',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='payment',
            name='record',
        ),
        migrations.AddField(
            model_name='payment',
            name='record',
            field=models.ManyToManyField(to='timesheet.Record'),
        ),
    ]
