# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-27 06:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0006_auto_20180627_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date_paid',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
